# Railway Deployment Configuration[phases.setup]

providers = ["python"]nixPkgs = ['python311', 'nodejs_18']



[python][phases.install]

version = "3.11"dependsOn = ['setup']

cmds = [

[build]    'pip install -r backend/requirements.txt',

cmds = ["pip install -r backend/requirements.txt"]    'cd frontend && npm ci'

]

[start]

cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"[phases.build]

dependsOn = ['install'] 

[variables]cmds = [

PYTHONPATH = "./src:./backend"    'cd frontend && npm run build'
]

[start]
cmd = 'python backend/main.py'