# Railway Nixpacks Configuration# Railway Deployment Configuration[phases.setup]

providers = ["python"]

providers = ["python"]nixPkgs = ['python311', 'nodejs_18']

[phases.setup]

nixPkgs = ['python311']



[phases.install] [python][phases.install]

dependsOn = ['setup']

cmds = ['pip install -r backend/requirements.txt']version = "3.11"dependsOn = ['setup']



[phases.start]cmds = [

cmd = 'python railway_start.py'

[build]    'pip install -r backend/requirements.txt',

[variables]

PYTHONPATH = "./src:./backend"cmds = ["pip install -r backend/requirements.txt"]    'cd frontend && npm ci'

]

[start]

[start]
cmd = "python railway_start.py"[phases.build]

dependsOn = ['install'] 

[variables]cmds = [

PYTHONPATH = "./src:./backend"    'cd frontend && npm run build'
]

[start]
cmd = 'python backend/main.py'