[build][build]

builder = "nixpacks"builder = "nixpacks"

buildCommand = "pip install -r backend/requirements.txt"

[deploy]

[deploy]restartPolicyType = "always"

startCommand = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

healthcheckPath = "/health"[environments.production.variables]

healthcheckTimeout = 300PYTHONPATH = "/app/src"

restartPolicyType = "on_failure"PORT = "8000"

[env]
PYTHONPATH = "./src:./backend"
PORT = "8000"